### ISSUE TITLE
Please create a version tag

### ISSUE THREAD

**Issue by ehaupt** [JeanJouliaCode/wipeClean#13]
Thank you for this very cool project.

I've seen that you've already set this version to `1.0.3` in [package-lock.json](https://github.com/JeanJouliaCode/wipeClean/blob/master/package-lock.json).

Could you please also tag this version in git (https://github.com/JeanJouliaCode/wipeClean/tags)?

This would make it a bit easier for people creating packages for their repositories. By the way, FreeBSD already has an official [package](https://repology.org/project/wipeclean/versions) (port) and I am sure there will be more repositories to follow 😉

**Comment by ehaupt** [comment]
See also (https://github.com/JeanJouliaCode/wipeClean/pull/14).

**Comment by Bango88** [comment]
For the AUR package I'm just going if the current version on the npm database, which is v1.0.4.

**Comment by ehaupt** [comment]
Closing this. Solution provided by @Bango88 works for FreeBSD port.
